enum TSType {
  COLLECTION = 'COLLECTION',
  ENUM = 'ENUM',
  OBJECT = 'OBJECT',
  PRIMITIVE = 'PRIMITIVE',
  REFERENCE = 'REFERENCE',
  TUPLE = 'TUPLE',
  UNTYPED = 'UNTYPED'
}

export {
  TSType
};
