enum TSType {
  COLLECTION = 'COLLECTION',
  COMBINATION = 'COMBINATION',
  ENUM = 'ENUM',
  OBJECT = 'OBJECT',
  PRIMITIVE = 'PRIMITIVE',
  REFERENCE = 'REFERENCE',
  TUPLE = 'TUPLE'
}

export {
  TSType
};
