name: Lint and test

on:
  push:
    branches: [ '*' ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show versions
        run: node --version && yarn --version
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
